baseURL = 'https://chilindri.es/'
languageCode = 'es-es'
title = 'Chilindri'
theme = 'ananke'



[params]
  featured_image = "/images/templario.jpg"



[[menus.main]]
  name = "Artículos"
  url = "/posts/articulos/"
  weight = 1

[[menus.main]]
  name = "Textos"
  url = "/posts/textos/"
  weight = 2

[[menus.main]]
  name = "Desde la tená"
  url = "/posts/desde_la_tena/"
  weight = 3

